### ISSUE TITLE
Banned.

### ISSUE THREAD

**Issue by PaziHD** [ZombieWizzard/Ace#9]
Banned for using ace. I've only been using ace.. so its definitely that.

**Comment by ZombieWizzard** [comment]
Can I get proof of some sort, if that's true I'm incredibly sorry...

**Comment by ZombieWizzard** [comment]
Also what is the ban length and could you check your email as riot should have emailed you.

**Comment by ZombieWizzard** [comment]
On looking at your account you apparently forked [AramBuddy](https://github.com/PaziHD/AramBuddy) from [FurkanS1821](https://github.com/FurkanS1821/AramBuddy) on that note I'm closing this as you apparently have some involvement with scripting in League which I'm inclined to believe got you banned, feel free to reopen if I'm wrong but lying and using Ace as a scapegoat for your use of scripts if dissapointing...

**Comment by PaziHD** [comment]
Zombie, I do not, and never have, scripted and the account I was banned on. I am far past scripting.
They have admitted to banning me by mistake, but they do not intend to unban me for some reason.
https://boards.oce.leagueoflegends.com/en/c/help-support-oce/coQijysp-you-admit-banning-me-was-a-mistake-but-you-dont-lift-the-ban

**Comment by ZombieWizzard** [comment]
I'm locking this issue as you are continuing to lie about your usage of scripting software and the reason of your ban.
